### Passo 1 - Importar Arquivos e Bibliotecas

In [6]:
# Para Ler as bases de dados
import pandas as pd

In [7]:
# importar Bases de Dados
emails = pd.read_excel('Bases de Dados/Emails.xlsx')
 # , encoding="utf-8")  ou , encoding="latin1") 
lojas = pd.read_csv('Bases de Dados/Lojas.csv', encoding="ISO-8859-1", sep=';')
vendas = pd.read_excel('Bases de Dados/Vendas.xlsx')

display(emails)
display(lojas)
display(vendas)

,Loja,Gerente,E-mail
0,Iguatemi Esplanada,Helena,pythonimpressionador+helena@gmail.com
1,Shopping Midway Mall,Alice,pythonimpressionador+alice@gmail.com
2,Norte Shopping,Laura,pythonimpressionador+laura@gmail.com
3,Shopping Iguatemi Fortaleza,Manuela,pythonimpressionador+manuela@gmail.com
4,Shopping União de Osasco,Valentina,pythonimpressionador+valentina@gmail.com
5,Shopping Center Interlagos,Sophia,pythonimpressionador+sophia@gmail.com
6,Rio Mar Recife,Isabella,pythonimpressionador+isabella@gmail.com
7,Salvador Shopping,Heloisa,pythonimpressionador+heloisa@gmail.com
8,Rio Mar Shopping Fortaleza,Luiza,pythonimpressionador+luiza@gmail.com
9,Shopping Center Leste Aricanduva,Julia,pythonimpressionador+julia@gmail.com
10,Ribeirão Shopping,Lorena,pythonimpressionador+lorena@gmail.com
11,Shopping Morumbi,Livia,pythonimpressionador+livia@gmail.com
12,Parque Dom Pedro Shopping,Maria Luiza,pythonimpressionador+maria_luiza@gmail.com
13,Bourbon Shopping SP,Cecilia,pythonimpressionador+cecilia@gmail.com
14,Palladium Shopping Curitiba,Eloa,pythonimpressionador+eloa@gmail.com
15,Passei das Águas Shopping,Miguel,pythonimpressionador+miguel@gmail.com
16,Center Shopping Uberlândia,Arthur,pythonimpressionador+arthur@gmail.com
17,Shopping Recife,Heitor,pythonimpressionador+heitor@gmail.com
18,Shopping Vila Velha,Bernardo,pythonimpressionador+bernardo@gmail.com
19,Shopping SP Market,Davi,pythonimpressionador+davi@gmail.com
20,Shopping Eldorado,Theo,pythonimpressionador+theo@gmail.com
21,Shopping Ibirapuera,Lorenzo,pythonimpressionador+lorenzo@gmail.com
22,Novo Shopping Ribeirão Preto,Gabriel,pythonimpressionador+gabriel@gmail.com
23,Iguatemi Campinas,Pedro,pythonimpressionador+pedro@gmail.com
24,Shopping Barra,Benjamin,pythonimpressionador+benjamin@gmail.com
25,Diretoria,Diretoria,pythonimpressionador+diretoria@gmail.com

    ID Loja                              Loja
0         1                Iguatemi Esplanada
1         2              Shopping Midway Mall
2         3                    Norte Shopping
3         4       Shopping Iguatemi Fortaleza
4         5          Shopping União de Osasco
5         6        Shopping Center Interlagos
6         7                    Rio Mar Recife
7         8                 Salvador Shopping
8         9        Rio Mar Shopping Fortaleza
9        10  Shopping Center Leste Aricanduva
10       11                 Ribeirão Shopping
11       12                  Shopping Morumbi
12       13         Parque Dom Pedro Shopping
13       14               Bourbon Shopping SP
14       15       Palladium Shopping Curitiba
15       16         Passei das Águas Shopping
16       17        Center Shopping Uberlândia
17       18                   Shopping Recife
18       19               Shopping Vila Velha
19       20                Shopping SP Market
20       21                 Shopping Eldorado
21       22               Shopping Ibirapuera
22       23      Novo Shopping Ribeirão Preto
23       24                 Iguatemi Campinas
24       25                    Shopping Barra

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,1,Sapato Estampa,1,358,358
1,1,2019-01-01,1,Camiseta,2,180,360
2,1,2019-01-01,1,Sapato Xadrez,1,368,368
3,2,2019-01-02,3,Relógio,3,200,600
4,2,2019-01-02,3,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
100994,69996,2019-12-26,17,Short Listrado,2,102,204
100995,69996,2019-12-26,17,Mochila,4,270,1080
100996,69996,2019-12-26,17,Pulseira Estampa,1,87,87
100997,69997,2019-12-26,11,Camisa Listrado,1,108,108
100998,69997,2019-12-26,11,Short Linho,2,133,266

### Passo 2 - Definir Criar uma Tabela para cada Loja e Definir o dia do Indicador

In [9]:
# Incluir a Coluna 'Nome Da Loja' na Planilha 'Vendas.xlsx'
# 'on="ID Lojas"' -> É a coluna em Comum nas duas Planilhas
vendas = vendas.merge(lojas, on='ID Loja')
display(vendas)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Loja
0,1,2019-01-01,1,Sapato Estampa,1,358,358,Iguatemi Esplanada
1,1,2019-01-01,1,Camiseta,2,180,360,Iguatemi Esplanada
2,1,2019-01-01,1,Sapato Xadrez,1,368,368,Iguatemi Esplanada
3,21,2019-01-02,1,Camisa Gola V Listrado,2,116,232,Iguatemi Esplanada
4,34,2019-01-02,1,Sapato Listrado,1,363,363,Iguatemi Esplanada
...,...,...,...,...,...,...,...,...
100994,69846,2019-12-25,8,Short Estampa,2,96,192,Salvador Shopping
100995,69846,2019-12-25,8,Tênis Estampa,5,256,1280,Salvador Shopping
100996,69850,2019-12-25,8,Calça Estampa,4,177,708,Salvador Shopping
100997,69972,2019-12-26,8,Terno Liso,3,720,2160,Salvador Shopping
100998,69972,2019-12-26,8,Sapato Estampa,5,358,1790,Salvador Shopping

In [4]:
# TINHA FEITO MERGE DUAS VEZES, GERANDO DUAS COLUNAS REPETIDAS. APAGUEI 
#..COM DROP:
vendas.drop("Loja_x", axis=1, inplace=True)
vendas.drop("Loja_y", axis=1, inplace=True)

KeyError: "['Loja_x'] not found in axis"

In [10]:
# Percorre as lojas da planilha Lojas em coluna Lojas (desta ultima)
dicionario_de_lojas = {}

    # A cada Loop detecta uma loja, Cria uma chave com seu nome
    #..Quando -> Vendas\Coluna -> Loja for igual ao que esta 
    #..sendo Percorrido no Loop atual
    
    #Dicionario recebe Valor que esta sendo percorrido, quando este
    #..for igual ao que esta na coluna Loja da planilha 'Vendas'

# Lojas -> Contém o CSV com o nome das lojas:
# lojas['Loja'] -> Pegaa a coluna ['Loja'] do CSV lojas e insere no
#..dicionario 'dicionario_de_lojas' (usando o sinal = )
for loja in lojas['Loja']:
    dicionario_de_lojas[loja] = vendas.loc[vendas['Loja'] == loja, :]

                                      
display(dicionario_de_lojas['Shopping Vila Velha'])                                           
display(dicionario_de_lojas['Salvador Shopping'])

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Loja
64268,32,2019-01-02,19,Polo Liso,1,137,137,Shopping Vila Velha
64269,32,2019-01-02,19,Polo Listrado,2,149,298,Shopping Vila Velha
64270,38,2019-01-02,19,Meia Xadrez,3,41,123,Shopping Vila Velha
64271,38,2019-01-02,19,Relógio,1,200,200,Shopping Vila Velha
64272,82,2019-01-02,19,Meia Listrado,1,37,37,Shopping Vila Velha
...,...,...,...,...,...,...,...,...
68497,69801,2019-12-25,19,Bermuda,3,150,450,Shopping Vila Velha
68498,69859,2019-12-25,19,Meia Liso,2,38,76,Shopping Vila Velha
68499,69970,2019-12-26,19,Casaco Linho,2,299,598,Shopping Vila Velha
68500,69974,2019-12-26,19,Meia Listrado,3,37,111,Shopping Vila Velha
68501,69985,2019-12-26,19,Pulseira Linho,2,114,228,Shopping Vila Velha

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Loja
96969,81,2019-01-02,8,Cueca Xadrez,1,60,60,Salvador Shopping
96970,126,2019-01-02,8,Camisa Estampa,1,113,113,Salvador Shopping
96971,138,2019-01-02,8,Pulseira Linho,5,114,570,Salvador Shopping
96972,177,2019-01-02,8,Camisa Liso,2,105,210,Salvador Shopping
96973,194,2019-01-02,8,Camisa Gola V Linho,4,145,580,Salvador Shopping
...,...,...,...,...,...,...,...,...
100994,69846,2019-12-25,8,Short Estampa,2,96,192,Salvador Shopping
100995,69846,2019-12-25,8,Tênis Estampa,5,256,1280,Salvador Shopping
100996,69850,2019-12-25,8,Calça Estampa,4,177,708,Salvador Shopping
100997,69972,2019-12-26,8,Terno Liso,3,720,2160,Salvador Shopping
100998,69972,2019-12-26,8,Sapato Estampa,5,358,1790,Salvador Shopping

In [11]:
# Mostrar Maior/Data_Mais_Recente da coluna:
dia_indicador = vendas['Data'].max()
print(dia_indicador)

print(f'{dia_indicador.day}/{dia_indicador.month}/{dia_indicador.year}')

# Se a tabela receber um valor/Data maior, isso sera atualizado automaticamente.

2019-12-26 00:00:00
26/12/2019

### Passo 3 - Salvar a planilha na pasta de backup

In [12]:
import pathlib

caminho_do_Backup = pathlib.Path(r'Backup Arquivos Lojas/')

# Transforma um diretorio num iteravel, e torna possivel percorrer &
#.. listar todas as pastas dentro dele.
arquivos_pasta_backup = caminho_do_Backup.iterdir()


# arquivos_pasta_backup -> Contém o Caminho com as
#.. pastas/nomes_de_todos_os_Shoppings :
lista_nomes_backup = []
for r in arquivos_pasta_backup:
    #print(r)
    #Pega só o nome da(s) pasta(s)
    #print(r.name)
    
    # Criamos uma lista com o nome de tudo o que estiver dentro da pasta
    lista_nomes_backup.append(r.name)

#print(lista_nomes_backup)


if 'Shopping Eldorado' in lista_nomes_backup:
    print('Its Here')

Its Here

In [ ]:
# Agora o mesmo procedimento, porém com ListComprehension:

# Se esta linha Não estiver na mesma Célula -> Não funciona:
arquivos_pasta_backup = caminho_do_Backup.iterdir()

lista_nomes_backup = [r.name for r in arquivos_pasta_backup]

# Nome de todas as pastas dentro da pasta (Lista_Nomes_Backuo):
print(lista_nomes_backup)

# for r in arquivos_pasta_backup:
#     print(r.name)

In [13]:
# Percorre o Dicionario que contem as informações unicas de cada Loja
for loja in dicionario_de_lojas:
    # Se esta loja não estiver na lista_nomes_backup (Que é a pasta que
    #..contém as Pastas com o Nome de todas as lojas)
    if loja not in lista_nomes_backup:
        # caminho_do_Backup -> Possui o caminho (Pathlib) Para a Pasta Backup
        #..loja é o nome da chave ou lojas no Dicionário
        
        nova_pasta = caminho_do_Backup / loja
        # Será criada uma pasta para cada nome/chave -> 'loja'
        nova_pasta.mkdir()
    
    # Dia Indicador é -> dia_indicador = vendas['Data']   , a Data do DF
    nome_arquivo = f'{dia_indicador.month}_{dia_indicador.day}_{loja}.xlsx'
    #nome_arquivo = '{}_{}_{}.xlsx'.format(dia_indicador.month, dia_indicador.day, loja)
    
    # caminho do arquivo ref ->'Backup Arquivos Lojas/'
    # 'loja' -> Item percorrido da pasta -> Backup Arquivos Lojas/
    # 'nome_arquivo' -> Nome gerado a partir de informações de data dos arquivos.
    local_arquivo = caminho_do_Backup / loja / nome_arquivo
    
    
    
    print(nome_arquivo)
    
    # Transforme Tal Dataframe em xlsx & coloque no 'local_arquivo'
    dicionario_de_lojas[loja].to_excel(local_arquivo)

12_26_Iguatemi Esplanada.xlsx
12_26_Shopping Midway Mall.xlsx
12_26_Norte Shopping.xlsx
12_26_Shopping Iguatemi Fortaleza.xlsx
12_26_Shopping União de Osasco.xlsx
12_26_Shopping Center Interlagos.xlsx
12_26_Rio Mar Recife.xlsx
12_26_Salvador Shopping.xlsx
12_26_Rio Mar Shopping Fortaleza.xlsx
12_26_Shopping Center Leste Aricanduva.xlsx
12_26_Ribeirão Shopping.xlsx
12_26_Shopping Morumbi.xlsx
12_26_Parque Dom Pedro Shopping.xlsx
12_26_Bourbon Shopping SP.xlsx
12_26_Palladium Shopping Curitiba.xlsx
12_26_Passei das Águas Shopping.xlsx
12_26_Center Shopping Uberlândia.xlsx
12_26_Shopping Recife.xlsx
12_26_Shopping Vila Velha.xlsx
12_26_Shopping SP Market.xlsx
12_26_Shopping Eldorado.xlsx
12_26_Shopping Ibirapuera.xlsx
12_26_Novo Shopping Ribeirão Preto.xlsx
12_26_Iguatemi Campinas.xlsx
12_26_Shopping Barra.xlsx

In [16]:
# Definição de metas

meta_faturamento_dia = 1000
meta_faturamento_ano = 1650000
meta_qtdeprodutos_dia = 4
meta_qtdeprodutos_ano = 120
meta_ticketmedio_dia = 500
meta_ticketmedio_ano = 500

### Passo 4 - Calcular o indicador para 1 loja

In [14]:
# Variavel...
loja = 'Norte Shopping'

# INDICADOR 1 - FATURAMENTO
vendas_loja = dicionario_de_lojas[loja]

# dia_indicador -> Contém a ultima OU a maior (.max) data do XLSX
vendas_loja_dia = vendas_loja.loc[vendas_loja['Data']==dia_indicador, :]

# Faturamento
faturamento_ano =vendas_loja['Valor Final'].sum()
# Soma da coluna 'Valor Final'
print(faturamento_ano)

faturamento_do_dia = vendas_loja_dia['Valor Final'].sum()
#É a soma das vendas deste ultimo dia. Ou Qualquer valor de venda em
#..uma linha que referencie o 'Norte Shopping' neste ultimo dia.
print(faturamento_do_dia) 

# INDICADOR 2 - DIVERSIDADE DE PRODUTOS

# DIVERSIDADE DE PRODUTOS POR ANO:
# Filtrar -> Apenas valores Unicos aparecerão
# print(vendas_loja['Produto'].unique()) -> Quantos tipos de produtos existem nesta loja
qtd_prod_ano = len(vendas_loja['Produto'].unique())
print(qtd_prod_ano) #Quant de prod vendidos no ano pela 'Norte Shopping'

# DIVERSIDADE DE PRODUTOS POR DIA:
# No ultimo dia (dia_indicador) -> Esta foi a quantidade de produtos vendida:
qtd_prod_dia = len(vendas_loja_dia['Produto'].unique())
print(qtd_prod_dia)
#__________________________________
# INDICADOR 3 - TICKET MÉDIO:

# Ticket médio
# Somou o valor de todas as colunas que tenham o
#..menos a coluna 'Código Venda'
#..Todas as colunas agora aparecem com a soma Delas mesmas E por isso
#..em menos linhas:
valor_venda = vendas_loja.groupby('Código Venda').sum()
display(valor_venda)

# MÉDIA:
media_valor_venda = valor_venda['Valor Final'].mean()
display(media_valor_venda)

# TICKET MÉDIO DIA
valor_venda_dia = vendas_loja_dia.groupby('Código Venda').sum()
display(valor_venda_dia)

# A média do valor final da Linha de Cima (que foi Um resultado Só == 1259  :
ticket_medio_dia = valor_venda_dia['Valor Final'].mean()
print(ticket_medio_dia)

1711968
1259
120
2

              ID Loja  Quantidade  Valor Unitário  Valor Final
Código Venda
2                   6           4             271          671
7                   6           2             221          221
73                  6           6             127          367
137                 3           2              50          100
147                 9           7             247          544
...               ...         ...             ...          ...
69845               9           3             623          623
69888               3           1             294          294
69916               3           2             700         1400
69962               3           2              78          156
69976               6           5             509         1259

[2182 rows x 4 columns]

784.5866177818515

              ID Loja  Quantidade  Valor Unitário  Valor Final
Código Venda
69976               6           5             509         1259

1259.0

In [15]:
# Olhando o resultado a cima Concluimos que todas as colunas
#..tiveram seu valor somar, e agora vemos uma tabela com Menos Linhas
#.. veja como ela ficou no display de baisxo agora:

x = vendas.loc[vendas['Código Venda']==69976]
display(x)



# Linha 2 da coluna Produto
#vendas.loc[2, 'Produto']

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Loja
8157,69976,2019-12-26,3,Tênis Xadrez,1,259,259,Norte Shopping
8158,69976,2019-12-26,3,Casaco,4,250,1000,Norte Shopping

### Passo 5 - Enviar por e-mail para o gerente

In [ ]:
# Quando não se usa o .values[0]    
#.. ele tráz uma tabela ao invés do valor contido nela:
#print(emails.loc[emails['Loja']==loja,'E-mail'])

# All right
# message = f'OnePage Dia {dia_indicador.day}/{dia_indicador.month} - Loja {loja}'
# print(message)

#OK
#att = pathlib.Path.cwd() / caminho_do_Backup / loja / f'{dia_indicador.month}_{dia_indicador.day}_{loja}.xlsx'
#print(att)

In [17]:
# ENVIAR E-MAIL COM RELATÓRIOS:
import smtplib,ssl
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email.utils import formatdate
from email import encoders
from senhas import key

mail = emails.loc[emails['Loja']==loja,'E-mail'].values[0] 
username = 'dikson.enterprise@gmail.com'
password = key
to_addrs = [mail, 'dikson.enterprise@gmail.com', 'diksonnn@gmail.com']
data = f'{dia_indicador.month}_{dia_indicador.day}_{loja}'
subject = f'OnePage Dia {dia_indicador.day}/{dia_indicador.month} - Loja {loja}'



#def send_mail(send_from,send_to,subject,text,files,server,port,username='',password='',isTls=True):
msg = MIMEMultipart()
msg['From'] = username
msg['To'] = to_addrs
#msg['Date'] = formatdate(localtime = True)
msg['Date'] = data
msg['Subject'] = subject
msg.attach(MIMEText("Vendas.xlsx"))

part = MIMEBase('application', "octet-stream")
part.set_payload(open("Vendas.xlsx", "rb").read())
encoders.encode_base64(part)
part.add_header('Content-Disposition', 'attachment; filename="Vendas.xlsx"')
msg.attach(part)

# ENVIANDO COM GMAIL:
#username = 'diksonnn@gmail.com'
#password = key

# CONEXÃO PARA OS SERVIDORES DO GOOGLE:
# server = 'smtp.gmail.com'
# port = 465
#port = 587


# ENVIANDO COM OUTLOOK
username = 'dikson_santos@outlook.com'
password = key

# CONEXÃO PARA servidor OUTLOOK:
server = 'smtp.office365.com'
port = 2525



isTls=True

#context = ssl.SSLContext(ssl.PROTOCOL_SSLv3)
#SSL connection only working on Python 3+
# smtp = smtplib.SMTP(server,port)
# if isTls:
#     smtp.starttls()
#     smtp.login(username,password)
#     smtp.sendmail(send_from, send_to, msg.as_string())

# conectaremos de forma segura usando SSL
server = smtplib.SMTP_SSL(server, port)
# para interagir com um servidor externo precisaremos
# fazer login nele
server.login(username, password)
server.sendmail(from_addr, to_addrs, message.as_string())


smtp.quit()

OSError: [Errno 101] Network is unreachable

### Passo 6 - Automatizar todas as lojas

In [ ]:
# BASTA USAR UM FOR NO CONTEUDO DA CELULA 'PASSO-4' , E IDENTAR O RESTANTE:
for loja in dicionario_lojas:
    # INDICADOR 1 - FATURAMENTO
    vendas_loja = dicionario_de_lojas[loja]

    # dia_indicador -> Contém a ultima OU a maior (.max) data do XLSX
    vendas_loja_dia = vendas_loja.loc[vendas_loja['Data']==dia_indicador, :]

    # Faturamento
    faturamento_ano =vendas_loja['Valor Final'].sum()
    # Soma da coluna 'Valor Final'
    #print(faturamento_ano)

    faturamento_do_dia = vendas_loja_dia['Valor Final'].sum()
    #É a soma das vendas deste ultimo dia. Ou Qualquer valor de venda em
    #..uma linha que referencie o 'Norte Shopping' neste ultimo dia.
    #print(faturamento_do_dia) 

    # INDICADOR 2 - DIVERSIDADE DE PRODUTOS

    # DIVERSIDADE DE PRODUTOS POR ANO:
    # Filtrar -> Apenas valores Unicos aparecerão
    # print(vendas_loja['Produto'].unique()) -> Quantos tipos de produtos existem nesta loja
    qtd_prod_ano = len(vendas_loja['Produto'].unique())
    #print(qtd_prod_ano) #Quant de prod vendidos no ano pela 'Norte Shopping'

    # DIVERSIDADE DE PRODUTOS POR DIA:
    # No ultimo dia (dia_indicador) -> Esta foi a quantidade de produtos vendida:
    qtd_prod_dia = len(vendas_loja_dia['Produto'].unique())
    print(qtd_prod_dia)
    #__________________________________
    # INDICADOR 3 - TICKET MÉDIO:

    # Ticket médio
    # Somou o valor de todas as colunas que tenham o
    #..menos a coluna 'Código Venda'
    #..Todas as colunas agora aparecem com a soma Delas mesmas E por isso
    #..em menos linhas:
    valor_venda = vendas_loja.groupby('Código Venda').sum()
    #display(valor_venda)

    # MÉDIA:
    media_valor_venda = valor_venda['Valor Final'].mean()
    display(media_valor_venda)

    # TICKET MÉDIO DIA
    valor_venda_dia = vendas_loja_dia.groupby('Código Venda').sum()
    #display(valor_venda_dia)

    # A média do valor final da Linha de Cima (que foi Um resultado Só == 1259  :
    ticket_medio_dia = valor_venda_dia['Valor Final'].mean()
    #print(ticket_medio_dia)
    
    # AQUI FICARIA A SECÇÃO DE ENVIO DE E-MAIL (MAS
    #..OS SERVIDORES NÃO ESTÃO ACEITANDO ESTE SERVIÇO AUTOMATIZADO)

### Passo 7 - Criar ranking para diretoria

In [36]:
faturamento_lojas = vendas.groupby('Loja').sum()

# Ordena do maior para o menor Com base na coluna 'Valor Final' :
faturamento_lojas_ano = faturamento_lojas.sort_values(by='Valor Final', ascending=False)

#display(faturamento_lojas_ano[['ID Loja','Quantidade','Valor Final']])
display(faturamento_lojas_ano[['Valor Final']])


vendas_dia = vendas.loc[vendas['Data']==dia_indicador, :]
faturamento_lojas_dia = vendas_dia.groupby('Loja')[['Loja','Valor Final']].sum()
faturamento_lojas_dia = faturamento_lojas_dia.sort_values(by='Valor Final', ascending=False)
display(faturamento_lojas_dia)

                                  Valor Final
Loja
Iguatemi Campinas                     1762419
Shopping Vila Velha                   1731167
Bourbon Shopping SP                   1726110
Rio Mar Recife                        1722766
Shopping SP Market                    1721763
Palladium Shopping Curitiba           1721120
Norte Shopping                        1711968
Ribeirão Shopping                     1707122
Iguatemi Esplanada                    1699681
Rio Mar Shopping Fortaleza            1698430
Shopping Center Leste Aricanduva      1682870
Novo Shopping Ribeirão Preto          1678225
Shopping Iguatemi Fortaleza           1674824
Center Shopping Uberlândia            1668921
Shopping União de Osasco              1663770
Shopping Barra                        1653103
Passei das Águas Shopping             1649014
Shopping Eldorado                     1648111
Salvador Shopping                     1646739
Shopping Center Interlagos            1640486
Shopping Ibirapuera                   1635060
Parque Dom Pedro Shopping             1631630
Shopping Recife                       1624879
Shopping Midway Mall                  1590441
Shopping Morumbi                      1586444

                                  Valor Final
Loja
Salvador Shopping                        3950
Novo Shopping Ribeirão Preto             3400
Center Shopping Uberlândia               2651
Shopping Eldorado                        2391
Shopping Center Interlagos               1582
Shopping Recife                          1366
Norte Shopping                           1259
Shopping União de Osasco                 1207
Shopping Vila Velha                       937
Bourbon Shopping SP                       676
Ribeirão Shopping                         650
Shopping Center Leste Aricanduva          485
Palladium Shopping Curitiba               381
Rio Mar Shopping Fortaleza                368
Shopping Midway Mall                      170
Shopping Ibirapuera                       118

In [42]:
#SALVANDO PARA UM .xlsx :
nome_file = f'{dia_indicador.day}_{dia_indicador.month}_Ranking_Anual.xlsx'
faturamento_lojas_ano.to_excel(r'Backup Arquivos Lojas\{}'.format(nome_file))

### Passo 8 - Enviar e-mail para diretoria